name: CI for React App

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug folder structure
        run: ls -R  # Verifica la estructura en los logs de GitHub Actions

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./front-end/package-lock.json  # Asegura que es la ruta correcta

      - name: Install dependencies
        run: npm install
        working-directory: ./front-end  # Corre npm install dentro de front-end

      - name: Run tests
        run: npm test
        working-directory: ./front-end  # Corre los tests dentro de front-end

      - name: Build project
        run: npm run build
        working-directory: ./front-end  # Corre el build dentro de front-end
